apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: arc
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: ARCHIVE_HOST
          valueFrom:
            configMapKeyRef:
              key: ARCHIVE_HOST
              name: dcm4chee-env
        - name: AUTH_SERVER_URL
          valueFrom:
            configMapKeyRef:
              key: AUTH_SERVER_URL
              name: dcm4chee-env
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_DB
              name: dcm4chee-env
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_PASSWORD
              name: dcm4chee-env
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_USER
              name: dcm4chee-env
        - name: STORAGE_DIR
          valueFrom:
            configMapKeyRef:
              key: STORAGE_DIR
              name: dcm4chee-env
        - name: WILDFLY_CHOWN
          value: /opt/wildfly/standalone /storage
        - name: WILDFLY_WAIT_FOR
          value: ldap:389 db:5432
        image: dcm4che/dcm4chee-arc-psql:5.22.3-secure
        name: arc
        ports:
        - containerPort: 8080
        - containerPort: 8443
        - containerPort: 9990
        - containerPort: 9993
        - containerPort: 11112
        - containerPort: 2762
        - containerPort: 2575
        - containerPort: 12575
        resources: {}
        volumeMounts:
        - mountPath: /storage
          name: arc-pacs-persistent
      restartPolicy: Always
      volumes:
      - name: arc-pacs-persistent
        persistentVolumeClaim:
          claimName: arc-pacs-persistent
status: {}
