apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: db
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: ARCHIVE_HOST
          valueFrom:
            configMapKeyRef:
              key: ARCHIVE_HOST
              name: dcm4chee-env
        - name: AUTH_SERVER_URL
          valueFrom:
            configMapKeyRef:
              key: AUTH_SERVER_URL
              name: dcm4chee-env
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_DB
              name: dcm4chee-env
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_PASSWORD
              name: dcm4chee-env
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_USER
              name: dcm4chee-env
        - name: STORAGE_DIR
          valueFrom:
            configMapKeyRef:
              key: STORAGE_DIR
              name: dcm4chee-env
        image: dcm4che/postgres-dcm4chee:12.2-22
        name: db
        ports:
        - containerPort: 5432
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: db-postgres-persistent
      restartPolicy: Always
      volumes:
      - name: db-postgres-persistent
        persistentVolumeClaim:
          claimName: db-postgres-persistent
status: {}
