apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: keycloak
spec:
  ports:
  - name: "8880"
    port: 8880
    targetPort: 8880
  - name: "8843"
    port: 8843
    targetPort: 8843
  - name: "8990"
    port: 8990
    targetPort: 8990
  - name: "8993"
    port: 8993
    targetPort: 8993
status:
  loadBalancer: {}
