apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: keycloak
spec:
  ports:
  - name: "Keycloak-http"
    port: 8880
    targetPort: 8880
  - name: "Keycloak-https"
    port: 8843
    targetPort: 8843
  - name: "WildFly-http"
    port: 8990
    targetPort: 8990
  - name: "WildFly-https"
    port: 8993
    targetPort: 8993
status:
  loadBalancer: {}
