apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: ldap-config-persistent
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
