apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: ldap
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: ARCHIVE_HOST
          valueFrom:
            configMapKeyRef:
              key: ARCHIVE_HOST
              name: dcm4chee-env
        - name: AUTH_SERVER_URL
          valueFrom:
            configMapKeyRef:
              key: AUTH_SERVER_URL
              name: dcm4chee-env
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_DB
              name: dcm4chee-env
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_PASSWORD
              name: dcm4chee-env
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_USER
              name: dcm4chee-env
        - name: STORAGE_DIR
          valueFrom:
            configMapKeyRef:
              key: STORAGE_DIR
              name: dcm4chee-env
        image: dcm4che/slapd-dcm4chee:2.4.50-22.3
        name: ldap
        ports:
        - containerPort: 389
        - containerPort: 636
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/openldap/openldap-data
          name: ldap-data-persistent
        - mountPath: /etc/openldap/slapd.d
          name: ldap-config-persistent
      restartPolicy: Always
      volumes:
      - name: ldap-data-persistent
        persistentVolumeClaim:
          claimName: ldap-data-persistent
      - name: ldap-config-persistent
        persistentVolumeClaim:
          claimName: ldap-config-persistent
status: {}
