apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: ldap
spec:
  ports:
  - name: "389"
    port: 389
    targetPort: 389
  - name: "636"
    port: 636
    targetPort: 636
status:
  loadBalancer: {}
